FROM ruby:3.1

# Set default locale for the environment
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

RUN apt-get update && apt-get install -y imagemagick libmagickwand-dev build-essential

WORKDIR /usr/src/app

COPY Gemfile jekyll-text-theme.gemspec ./
RUN bundle install

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0"]
