# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Seminar update notification

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run Python app
      run: python .github/workflows/seminar-notification.py
      env:
        COMMIT_MESSAGE: ${{github.event.head_commit.message}}
        BOT_TOKEN: ${{secrets.BOT_TOKEN}}
        BASE_URL: ${{secrets.BASE_URL}}
        TEAM_ID: ${{secrets.TEAM_ID}}
        BOT_ID: ${{secrets.BOT_ID}}
